### ISSUE TITLE
DDE example does not work with new version - possible bug

### ISSUE THREAD

**Issue by devmotion** [YingboMa/RecursiveFactorization.jl#4]
Hej!

The example in https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/121 does not work anymore with the latest released versions of DelayDiffEq, OrdinaryDiffEq, and DiffEqBase, but if I only revert RecursiveFactorizations to version 0.0.1, I can compute again a solution (although, honestly component 2 looks a bit strange - have to compare that in detail with the RADAR5 solution).

More convincingly, I can run
```julia
solve(prob_dde_RADAR5_waltman_5, MethodOfSteps(Rosenbrock23()); reltol = 1e-6, abstol = [1e-18, 1e-18, 1e-18, 1e-18, 1e-6, 1e-6])
```
(the default settings of RADAR5 if you specify a relative tolerance of 1e-6) only with RecursiveFactorizations v0.0.1. Without checking the result in depth, the resulting plots look quite similar to the ones generated by RADAR5, compare https://www.mapleprimes.com/posts/201287-Delay-Differential-Equations--Maple-Is-A-Leader with

![plot14](https://user-images.githubusercontent.com/26102/61675506-9d0eb680-acc6-11e9-9ac2-ed04f7a3e6c0.png)

![plot56](https://user-images.githubusercontent.com/26102/61675512-a3049780-acc6-11e9-8f8f-8f83d9e04768.png)

Maybe that could also explain why my latest benchmarks with Rodas5 were a bit off?

**Comment by YingboMa** [comment]
Moin!

```julia
julia> sol = solve(DDEProblemLibrary.prob_dde_RADAR5_waltman, MethodOfSteps(Rosenbrock23(linsolve=LinSolveFactorize(lu))); reltol = 1e-6, abstol = [1e-18, 1e-18, 1e-18, 1e-18, 1e-6, 1e-6]);

julia> sol = solve(DDEProblemLibrary.prob_dde_RADAR5_waltman, MethodOfSteps(Rosenbrock23(linsolve=LinSolveFactorize(lu!))); reltol = 1e-6, abstol = [1e-18, 1e-18, 1e-18, 1e-18, 1e-6, 1e-6]);
┌ Warning: Instability detected. Aborting
└ @ DiffEqBase ~/.julia/dev/DiffEqBase/src/integrator_interface.jl:162

julia> sol = solve(DDEProblemLibrary.prob_dde_RADAR5_waltman, MethodOfSteps(Rosenbrock23(linsolve=LinSolveFactorize(x->lu!(copy(x))))); reltol = 1e-6, abstol = [1e-18, 1e-18, 1e-18, 1e-18, 1e-6, 1e-6]);

julia>

```
Unfortunately, I think there might be a bug in OrdinaryDiffEq's factorization reuse logic.

**Comment by devmotion** [comment]
Oh, then it might affect a lot more examples :open_mouth:

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/839 ?

**Comment by devmotion** [comment]
Yes, was thinking about that one as well

**Comment by devmotion** [comment]
Maybe it is related to https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/122?

**Comment by devmotion** [comment]
> Maybe it is related to JuliaDiffEq/DelayDiffEq.jl#122?

It seems, it's not. Even with completely separate unlinked caches the problem persists.

**Comment by devmotion** [comment]
With `KenCarp4` and `KenCarp5`, e.g., I can compute a solution of the DDE for all different kinds of linear factorizations, i.e., regardless of whether I use `LinSolveFactorize(lu)`, `LinSolveFactorize(lu!)`, or `LinSolveFactorize(x -> lu!(copy(x)))`. For `KenCarp5` all solutions are identical, whereas for `KenCarp4` the solution computed with `LinSolveFactorize(lu!)` is only approximately equal to the ones computed with `LinSolveFactorize(lu)` and `LinSolveFactorize(x -> lu!(copy(x)))` (which are identical).

But maybe that indicates that the problem might be specific for the Rosenbrock methods (or at least Rosenbrock23)?

**Comment by ChrisRackauckas** [comment]
The Rosenbrock methods need an "exact" Jacobian whereas the SDIRK methods do not.

**Comment by YingboMa** [comment]
If you need significantly more steps with `lu!`, it could indicate that `lu!` creates problems for `KenCarp4`, too. If not, then most likely `KenCarp4` is fine.

**Comment by devmotion** [comment]
I'm pretty sure it takes exactly the same number of steps - otherwise my comparisons of `sol.t` and `sol.u` would have thrown errors due to different lengths.
